### ISSUE TITLE
TOKEN

### ISSUE THREAD

**Issue by stevetawk123** [Nixtla/nixtla#100]
Dears,

How do i get a TOKEN to use TimeGBT

**Comment by Pie33000** [comment]
You can get a token from the Nixtla dashboard : https://dashboard.nixtla.io

**Comment by xiaolongluo1979** [comment]
How do we get it? I did not see a place to copy or something. Write an email? Thanks.

**Comment by elephaint** [comment]
@xiaolongluo1979 @stevetawk123 You can get an API key [here](https://[dashboard.nixtla.io/team/1246433/usage](https://dashboard.nixtla.io/team/1246433/usage))
