### ISSUE TITLE
Where is the LICENSE?

### ISSUE THREAD

**Issue by goodwanghan** [Nixtla/nixtla#106]
Hi Nixtla team,

I don't think the LICENSE file contains the license information? How can we find related information?

Thanks

**Comment by mergenthaler** [comment]
Thank you for expressing interest in TimeGPT and NixtlaTS, the Python Software Development Kit (SDK). We have revised the LICENSE file to accurately represent the Terms and Conditions of the Python SDK, designed for interaction with TimeGPT. Should you wish to review the Terms and Conditions pertaining to TimeGPT directly, kindly refer to https://docs.nixtla.io/docs/terms-and-conditions.
