### ISSUE TITLE
KeyError: 'TIMEGPT_TOKEN'

### ISSUE THREAD

**Issue by xiaolongluo1979** [Nixtla/nixtla#128]
This may be a naive question as I am not a developer ...

After installing nixtlats (via !pip install nixtlats on jupyter notebook), I was trying the simple codes provided but got the following error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_6602/2071313601.py in <module>
      2 
      3 from nixtlats import TimeGPT
----> 4 timegpt = TimeGPT(token=os.environ['TIMEGPT_TOKEN'])
      5 fcst_df = timegpt.forecast(df, h=24, level=[80, 90])

~/anaconda3/lib/python3.9/os.py in __getitem__(self, key)
    677         except KeyError:
    678             # raise KeyError with the original key value
--> 679             raise KeyError(key) from None
    680         return self.decodevalue(value)
    681 

KeyError: 'TIMEGPT_TOKEN'

How do I get the 'TIMEGPT_TOKEN' ?

**Comment by talrejanikhil** [comment]
Have you obtained a Time GPT token and set it as a environment variable?
You can get a token here - https://dashboard.nixtla.io/

**Comment by MateKristof** [comment]
You should create an .env file in the project directory and paste the API key into it. As seen here:
![image](https://github.com/Nixtla/nixtla/assets/9765439/63d01b68-6cbb-46b0-ba61-b26267a52d7a)
Then install python dotenv.
```
pip install python-dotenv
```
And use this lines in your example file to load environment:
```
from dotenv import load_dotenv
load_dotenv()
```
