### ISSUE TITLE
Time GPT plot - Only 8 subplots can be plotted at max

### ISSUE THREAD

**Issue by talrejanikhil** [Nixtla/nixtla#134]
What happened + What you expected to happen
When using timegpt.plot() the max no. of subplots plotted is only 8.

If I have more than 8 unique series in my data, the maximum no. of subplots would be restricted to 8.

Versions / Dependencies
nixtlats ==0.1.17
python==3.9.18

Reproduction script
Plot any data with more than 8 unique_ids

Issue Severity
Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
Hey @talrejanikhil. The function here is a wrapper of the [utilsforecast implementation](https://nixtla.github.io/utilsforecast/plotting.html), which has a `max_ids` argument. Can you try that one in the meantime?

**Comment by talrejanikhil** [comment]
Yup I will use that. But its also fairly easy to fix this one by passing max_ids into timegpt.plot()

**Comment by mergenthaler** [comment]
We will add this as a feature request. Closing for now, but please re-open if necessary.
