### ISSUE TITLE
nixtlats.core.api_error.ApiError

### ISSUE THREAD

**Issue by fiksdano** [Nixtla/nixtla#138]
nixtlats.core.api_error.ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email ops@nixtla.io to continue using the API', 'code': 'A20', 'requestID': 'F58XQJWLVW', 'support': 'If you have questions or need support, please email ops@nixtla.io'}

I encountered the above problems, would like to ask how to solve?

**Comment by vishal-git** [comment]
It looks like the API request limit is _very_ restrictive. I got the token today (from https://dashboard.nixtla.io/) and tried to use it _two times_. Both times, I got simple error messages such as there must be a column named `ds` and `y` etc. (which made sense.) I then corrected those errors and tried to run my code the _third_ time. And to my surprise, I had already reached the API usage quota for this month!

**Comment by Gtemeng** [comment]
Yes, I also encountered the same problem. I don't know why the token I applied for can only be used here[https://docs.nixtla.io/reference/timegpt_timegpt_post](url)

**Comment by Gtemeng** [comment]
在本地使用时，出现两种错误
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1131)
与
nixtlats.core.api_error.ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached 
your request limit, email ops@nixtla.io to continue using the API', 'code': 'A20', 'requestID': 'HG7CNHY8YS', 'support': 'If you have 
questions or need support, please email ops@nixtla.io'}

**Comment by mergenthaler** [comment]
After our stable release, everyone should be able to access a free trial token at dashboard.nixtla.io 
Re-open if necessary.
