### ISSUE TITLE
timegpt.validate_token() - timeout

### ISSUE THREAD

**Issue by shuiyuebingdian** [Nixtla/nixtla#142]
![企业微信截图_20231101110155](https://github.com/Nixtla/nixtla/assets/44151248/878ef28d-6558-4f05-b1c1-7e96ccd915f6)

**Comment by elephaint** [comment]
@shuiyuebingdian I think this issue is probably no longer relevant; you can follow [this guide to validate your API key](https://nixtlaverse.nixtla.io/nixtla/docs/getting-started/setting_up_your_api_key.html)
