### ISSUE TITLE
Include mention of Dask and Ray in distributed example. 

### ISSUE THREAD

**Issue by mergenthaler** [Nixtla/nixtla#144]
It would be good to make more explicit the support of the AnyDateFrame paradigm. 
(Source: JS from Guac)

**Comment by AzulGarza** [comment]
hey @mmenchero, could you take this issue?

the task consists of based on the notebooks [how to forecast - spark](https://github.com/Nixtla/nixtla/blob/main/nbs/docs/how-to-guides/0_distributed_fcst_spark.ipynb) and [how to do cross validation - spark](https://github.com/Nixtla/nixtla/blob/main/nbs/docs/how-to-guides/1_distributed_cv_spark.ipynb):
- make a PR with exactly the same notebooks but using dask (you can see an example using statsforecast [here](https://nixtla.mintlify.app/statsforecast/docs/how-to-guides/dask.html))
- make a PR with exactly the same notebooks but using ray (you can see an example using statsforecast [here](https://nixtla.mintlify.app/statsforecast/docs/how-to-guides/ray.html))
- the notebooks should be lie in the same directory following the name convention there

**Comment by MMenchero** [comment]
Sure, I'm on it.

**Comment by elephaint** [comment]
Closing - I think this was solved in our docs update some time ago
