### ISSUE TITLE
nixtlats.core.api_error.ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email ops@nixtla.io to continue using the API', 'code': 'A20', 'requestID': 'RFL5CAVMNB', 'support': 'If you have questions or need support, please email ops@nixtla.io'}

### ISSUE THREAD

**Issue by 1348598339** [Nixtla/nixtla#145]
Hi, I got a problem below while running the quick start,:
nixtlats.core.api_error.ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email ops@nixtla.io to continue using the API', 'code': 'A20', 'requestID': 'RFL5CAVMNB', 'support': 'If you have questions or need support, please email ops@nixtla.io'}
How should I solve this? Thank you!

**Comment by bleicham** [comment]
As have I.

**Comment by Hanmengnan** [comment]
me too

**Comment by jsiowhhc** [comment]
me too

**Comment by jsiowhhc** [comment]
> Hi, I got a problem below while running the quick start,: nixtlats.core.api_error.ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email [ops@nixtla.io](mailto:ops@nixtla.io) to continue using the API', 'code': 'A20', 'requestID': 'RFL5CAVMNB', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'} How should I solve this? Thank you!

**Comment by 18811449050** [comment]
I have encountered the same problem.

**Comment by LakshmanKishore** [comment]
I'm still getting the same error.
Does anyone have a solution for this?

**Comment by WhuJacob** [comment]
Some problem

**Comment by elephaint** [comment]
I think all these errors were caused by too many requests - this is no longer relevant, right? @AzulGarza

**Comment by mergenthaler** [comment]
Right @elephaint. The new version should fix this. Everyone should be able to create a trial account on dashboard.nixtla.io and start using TimeGPT. 
Re-open if necessary.
