### ISSUE TITLE
make_holidays: incompatibility of date type and date range fix

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/nixtla#15]
When fixing the distance variables for the beginning and end of the date range
distance[distance>183] = 365 - distance[distance>183]

UFuncTypeError: Cannot cast ufunc 'greater' input 0 from dtype('<m8[ns]') to dtype('<m8') with casting rule 'same_kind'

**Comment by pietroppeter** [comment]
PR to fix this #44 (I was expecting that PR to be linked automatically here)
