### ISSUE TITLE
[BUG] Retry in distributed environments

### ISSUE THREAD

**Issue by AzulGarza** [Nixtla/nixtla#157]
Probably `tenacity` is not being invoked in distributed environments (namely `Dask`). See [this](https://github.com/Nixtla/nixtla/actions/runs/6794557008/job/18471163100#step:5:877).

**Comment by mergenthaler** [comment]
@jmoralez, are you also working on this for v2?

**Comment by jmoralez** [comment]
That's a crucial part, since the distributed requests almost always fail, see for example ([logs](https://github.com/Nixtla/nixtla/actions/runs/10256732275/job/28379096568#step:5:182)):

> ERROR:nixtla.nixtla_client:Attempt 1 failed with error: The read operation timed out
