### ISSUE TITLE
ApiError: status_code: 500

### ISSUE THREAD

**Issue by andrewm4894** [Nixtla/nixtla#162]
```
ApiError: status_code: 500, body: {'data': None, 'message': 'Request failed with status code 500', 'code': 'B30', 'requestID': 'ZQBEUBHYQT', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'}
```

I'm trying to just implement a minimal example but getting this error - any idea why that might be?

Here is my example:

```
import pandas as pd
import numpy as np
from nixtlats import TimeGPT

num_rows = 5000
start_time = pd.Timestamp.now().floor('T')
timestamps = pd.date_range(start=start_time, periods=num_rows, freq='T')
metric_values = np.random.random(size=num_rows)

df = pd.DataFrame({'metric_timestamp': timestamps, 'metric_value': metric_values})

df = df.set_index('metric_timestamp').resample('1H').mean().reset_index()

print(df.shape)
print(df.head())

timegpt = TimeGPT(token='XXX')
timegpt_anomalies_df = timegpt.detect_anomalies(
    df, 
    time_col='metric_timestamp', 
    target_col='metric_value', 
    freq='1H'
)
print(timegpt_anomalies_df.head())
```

**Comment by andrewm4894** [comment]
actually just realising this is probably because i'm not in the closed beta - did not realise that as i was making my token etc. If that's what's going on here then feel free to close. If so, maybe a more detailed response to that effect might make it more obvious and avoid any dupes of this in future.

the only other thing i can think of maybe is fact im running on colab and user agents etc but im assuming that's less likely any issue here..

**Comment by elephaint** [comment]
@andrewm4894 Closing - if you didn't have a valid key a 500 error may have occurred indeed.
