### ISSUE TITLE
[FIX] chore: explicit in the code the differences between the SDK's `X_df` and the API's `X_df`

### ISSUE THREAD

**Issue by AzulGarza** [Nixtla/nixtla#172]
The SDK and the API handle the exogenous variables differently. The `SDK` differentiates between historical exogenous variables (used during finetuning, for example) and future ones. The historical variables are included along the target variable in `df`, and the future ones are passed in `X_df`. However, the API receives the exogenous variables stacked together (`X_df_api = df_no_target + X_df`). 

The problem is that the core code needs to apply a proper naming convention to reflect the differences (`X_df` is used for both cases). This is important because development has been problematic lately (see, for example, #171).

**Comment by mergenthaler** [comment]
Fixed by #429.
