### ISSUE TITLE
nixtlats.core.api_error.ApiError: status_code: 429

### ISSUE THREAD

**Issue by luoolu** [Nixtla/nixtla#173]
nixtlats.core.api_error.ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email ops@nixtla.io to continue using the API', 'code': 'A20', 'requestID': 'HCJZ2U3PBY', 'support': 'If you have questions or need support, please email ops@nixtla.io'}

how to fix?

**Comment by Nicky9529** [comment]
Hi, got the same message here too.
_ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email [ops@nixtla.io](mailto:ops@nixtla.io) to continue using the API', 'code': 'A20', 'requestID': 'PTZRRRWWL8', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'}

**Comment by wentixiaogege** [comment]
that's cause we have only number of 1 requests.....  but to finish a forecast, the sdk seems using multi requests....

**Comment by BasilaryGroup** [comment]
I'm having the same problem. I can't even get it to run with their canned example.

```
Exception has occurred: ApiError
status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email ops@nixtla.io to continue using the API', 'code': 'A20', 'requestID': 'DL4KET8WPK', 'support': 'If you have questions or need support, please email ops@nixtla.io'}
  File "C:\Users\David\ShearFrac\timegpt\gpt.py", line 12, in <module>
    fcst_df = timegpt.forecast(df, h=24, level=[80, 90])
nixtlats.core.api_error.ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email ops@nixtla.io to continue using the API', 'code': 'A20', 'requestID': 'DL4KET8WPK', 'support': 'If you have questions or need support, please email ops@nixtla.io'}
```

**Comment by AzulGarza** [comment]
hey @luoolu, @Nicky9529, @wentixiaogege, @BasilaryGroup! Currently, the default number of tokens per user is restricted. We are trying to onboard as many users as possible. Please sign up [here](https://www.nixtla.io/#tgpt). :)

**Comment by mergenthaler** [comment]
We released some new improvements and increased the number of allowed requests. Please install the latest version of the SDK and try again. I am happy to help if that does not work. Please re-open if necessary.
