### ISSUE TITLE
[FEAT] Add recommendations when a 413 error is returned 

### ISSUE THREAD

**Issue by AzulGarza** [Nixtla/nixtla#177]
Related to size of data. It should suggest using `num_partitions`. See #176.

**Comment by elephaint** [comment]
@marcopeix @AzulGarza #418 is the same?

**Comment by AzulGarza** [comment]
hey @elephaint! yes, it is the same. an interesting fix would be to chatch the error inside the sdk, and give the recommendation. adding @jmoralez to the loop to see if we can include something similar in v2 (that version will have less problems with data size, but maybe we can think about it.)
