### ISSUE TITLE
i have the apikey of timegpt, but i dont konw how to enter the apikey into code. I didnt find any doc about it

### ISSUE THREAD

**Issue by labrinyang** [Nixtla/nixtla#178]
I just meet error 401, it seems like that i need to provide apikey to get consent to use it. after I get apikey from your website, I dont konw how to enter it.

anyway thanks for your splendid work!! I hope to take a try with it.

**Comment by 2665477495** [comment]
p.s.    the language i use is python

**Comment by Mzakery** [comment]
Hello
I also got the 401 error.
I registered on the site and received the token, but unfortunately I still get the 401 error.
please guide me

ApiError: status_code: 401, body: {'data': None, 'message': 'Invalid API key', 'details': 'Key not found', 'code': 'A12', 'requestID': 'E7F2BBTB2P', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'}

**Comment by elephaint** [comment]
@Mzakery Apologies for not getting back to you earlier here. I'm assuming this issue is no longer present?

**Comment by mergenthaler** [comment]
Closing this, but feel free to re-open if necessary.
