### ISSUE TITLE
how to Fine-Tuning?

### ISSUE THREAD

**Issue by fiksdano** [Nixtla/nixtla#184]
Hello author, thank you very much for sharing. Now I want your TimeGPT model to perform my task prediction, so I need to perform fine-tuning operation. What tools do you support for fine-tuning? Can you give me a specific method and process? I am looking forward to your reply very much.

**Comment by AzulGarza** [comment]
hi @fiksdano! thank you for using nixtla. [here](https://docs.nixtla.io/docs/finetuning)'s a reference on finetuning.

**Comment by elephaint** [comment]
@fiksdano Closing this issue, note that the link from @AzulGarza is no longer valid, here's the link on finetuning

[Finetuning with TimeGPT](https://docs.nixtla.io/docs/tutorials-fine_tuning)

**Comment by elephaint** [comment]
Closing
