### ISSUE TITLE
pandas incompatibility 

### ISSUE THREAD

**Issue by davecmm** [Nixtla/nixtla#193]
Looks good so far!, no problem with forecasting.

Following along this [quick start guide](https://docs.nixtla.io/docs/timegpt_quickstart) tho', and when using timegpt.plot:

`timegpt.plot(df, timegpt_fcst_df, time_col='timestamp', target_col='value')`

throws error:

> ~/.local/lib/python3.10/site-packages/pandas/core/indexers/utils.py in disallow_ndim_indexing(result)
>     341     """
>     342     if np.ndim(result) > 1:
> --> 343         raise ValueError(
>     344             "Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer "
>     345             "supported. Convert to a numpy array before indexing instead."
> 
> ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.

Fallen back on good ole fashioned matplotlib for now ....

**Comment by davecmm** [comment]
doh! I'm an idiot, thanks.

**Comment by jmoralez** [comment]
I don't think you were completely at fault here, we only had matplotlib as the requirement, we've [changed](https://github.com/Nixtla/utilsforecast/commit/da7540d95732ec7afd10ad12174e292f0ba1a816) it to be `pandas[plot]` instead. That should check the compatibility when installing, hopefully avoiding this case. Thanks for reporting!
