### ISSUE TITLE
multi-objective output

### ISSUE THREAD

**Issue by mypursue-ui** [Nixtla/nixtla#194]
Is it possible to perform multi-objective input and multi-objective output? I see that the tutorial uses single output

**Comment by Yibei990826** [comment]
Hi @mypursue-ui! Yes, it's possible to do multi-series forecasting with TimeGPT. Please refer to this [tutorial](https://docs.nixtla.io/docs/multiple_series)

**Comment by mergenthaler** [comment]
Closing this, but feel free to re-open if necessary.
