### ISSUE TITLE
TOKEN page does not work

### ISSUE THREAD

**Issue by Jap8nted** [Nixtla/nixtla#196]
I am trying to get the TOKEN for TimeGPT but after login to my Github account it does not work.

**Comment by gaoyk666** [comment]
Today it's still not work,it can't be solve?

**Comment by asadabbas09** [comment]
yeah same problem

**Comment by aabuabat** [comment]
same here

**Comment by DongJian17** [comment]
me too

**Comment by elephaint** [comment]
@Jap8nted @gaoyk666 @asadabbas09 @aabuabat @DongJian17 Sorry for the late reply. I hope you were able to get a token. 

You can now [get an API key here](https://dashboard.nixtla.io/)

**Comment by mergenthaler** [comment]
Closing this, but feel free to re-open if necessary.
