### ISSUE TITLE
Can not get the token form https://dashboard.nixtla.io/ since it can not be opened

### ISSUE THREAD

**Issue by yifeiSunny** [Nixtla/nixtla#199]
As I said in the title, I can not get the token from https://dashboard.nixtla.io/ since the website can not be opened.

Another, it might be helpful for users to know where to get the token if the token website can be put on the Github ReadMe file or in the https://nixtlaverse.nixtla.io/nixtla/index.html.  To be honest, it is really hard for me to find where I can find to get the token.

**Comment by AzulGarza** [comment]
hey @yifeiSunny! thank you so much for your feedback. we recently fixed a bug on our website. could you try again? regarding the token, we'll add that information to the readme. thank you! :)

**Comment by gsamaras** [comment]
@AzulGarza it seems that I cannot get the token myself too. I was hoping to use TimeGPT for a paper and cite, but when I go to Get Token, either with Google or Github, I get: 
```
{
  "message":"An invalid response was received from the upstream server"
}
```
either from my laptop or mobile phone.

How do get the token please?

**Comment by AzulGarza** [comment]
hey @gsamaras! thank you so much for reporting this. could you try again? the page is up and running again. 🎉

**Comment by elephaint** [comment]
@gsamaras @AzulGarza I think this issue can be closed, no?
