### ISSUE TITLE
 status_code: 400

### ISSUE THREAD

**Issue by lihuang218** [Nixtla/nixtla#203]
nixtlats.core.api_error.ApiError: status_code: 400, body: {'data': None, 'message': None, 'details': None, 'code': None, 'requestID': 'DK974MT6N3', 'support': 'If you have questions or need support, please email ops@nixtla.io'}
![1704179538174](https://github.com/Nixtla/nixtla/assets/69420245/d0988e4f-17fd-4528-8a94-d4cffc7a8861)

**Comment by AzulGarza** [comment]
hey @lihuang218, thanks for using `TimeGPT`. we experienced some intermittency in previous days. could you try again?  :)

**Comment by AlbertoLanaro** [comment]
I'm having the same problem now

Output of the script:
```bash
INFO:nixtlats.timegpt:Calling Forecast Endpoint...
INFO:nixtlats.timegpt:Attempt 1 failed...
INFO:nixtlats.timegpt:Attempt 2 failed...
INFO:nixtlats.timegpt:Attempt 3 failed...
INFO:nixtlats.timegpt:Attempt 4 failed...
INFO:nixtlats.timegpt:Attempt 5 failed...
INFO:nixtlats.timegpt:Attempt 6 failed...
```
Error:
```bash
ApiError: status_code: 400, body: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Bad Request</pre>
</body>
</html>
```

**Comment by zhongguojunhun1** [comment]
> nixtlats.core.api_error.ApiError: status_code: 400, body: {'data': None, 'message': None, 'details': None, 'code': None, 'requestID': 'DK974MT6N3', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'} ![1704179538174](https://private-user-images.githubusercontent.com/69420245/293642062-d0988e4f-17fd-4528-8a94-d4cffc7a8861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDkwNjksIm5iZiI6MTcwOTEwODc2OSwicGF0aCI6Ii82OTQyMDI0NS8yOTM2NDIwNjItZDA5ODhlNGYtMTdmZC00NTI4LThhOTQtZDRjZmZjN2E4ODYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MjYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OTI1ODc0MjNlNzBmZDBmMGIzM2Q3NzI0MGQ4MDk2MGFiMTkyOTBiZTM0NmQ3MjM2MzI5Y2QyNzFjOTc0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XMDPnTMOSlOiKrpIYC6FMXM7lnQ4AboMYlPMWq3L2no)
I also encountered the same problem. Have you solved it?

**Comment by Tingji2419** [comment]
Me too. I've checked the network and my token validation. Still get the info :`INFO:nixtlats.nixtla_client:Validating inputs...
INFO:nixtlats.nixtla_client:Preprocessing dataframes...
INFO:nixtlats.nixtla_client:Restricting input...
INFO:nixtlats.nixtla_client:Calling Forecast Endpoint...
INFO:nixtlats.nixtla_client:Attempt 1 failed...
INFO:nixtlats.nixtla_client:Attempt 2 failed...
INFO:nixtlats.nixtla_client:Attempt 3 failed...
INFO:nixtlats.nixtla_client:Attempt 4 failed...
INFO:nixtlats.nixtla_client:Attempt 5 failed...
INFO:nixtlats.nixtla_client:Attempt 6 failed...`

**Comment by Tingji2419** [comment]
I've solved my problem. It was due to the incorrect form of the timestamp column ('ds' column). It should be in 'xxxx-xx-xx 00:00:00' but not 'xxxx/xx/xx 0:00'.

When using original data with 'ds' column of ''xxxx/xx/xx 0:00'', it reported error:
`Exception: Could not infer frequency of ds column. . This could be due to inconsistent intervals. Please check your data for missing, duplicated or irregular timestamps`

And then i specified the freq='M', it reported error likes:
`INFO:nixtlats.nixtla_client:Attempt 1 failed.`

Final i reform the 'ds' columns to 'xxxx/xx/xx 0:00' without specified the freq, it fixed.
