### ISSUE TITLE
Does TimeGPT clean/preprocess the data set?

### ISSUE THREAD

**Issue by gsamaras** [Nixtla/nixtla#215]
When calling TimeGPT to forecast I see this [message](https://docs.nixtla.io/docs/timegpt_quickstart):

```
INFO:nixtlats.timegpt:Preprocessing dataframes...
```

Does it mean that TimeGPT cleans the data automatically?

**Comment by Yibei990826** [comment]
Hi @gsamaras! Here, preprocessing indicates formatting the DataFrame to ensure compatibility with TimeGPT's processing requirements. Currently, we still need to do preprocessing/ cleaning manually. Maybe [fill_gaps](https://nixtlaverse.nixtla.io/utilsforecast/preprocessing.html#fill-gaps) might be helpful?

**Comment by Yibei990826** [comment]
Hi @gsamaras! Here, preprocessing indicates formatting the DataFrame to ensure compatibility with TimeGPT's processing requirements. Currently TimeGPT uses a fix scaler when forecasting, so users do not need to scale the data.

**Comment by elephaint** [comment]
@Yibei990826 @gsamaras I think this issue can be closed (?)

**Comment by Yibei990826** [comment]
Yes, I think this answers the question
