### ISSUE TITLE
Can we compute and visualize Seasonality in data using Nixtla? 

### ISSUE THREAD

**Issue by rostam** [Nixtla/nixtla#216]
Can we compute and visualize Seasonality in data using Nixtla? 
For example, how the data trend is changing in summer or winter?

**Comment by Yibei990826** [comment]
Hi @rostam! Yes, you can visualize trend/ seasonality with NixtlaVerse's statsforecast. Please refer to MSTL tutorial [here](https://nixtlaverse.nixtla.io/statsforecast/docs/tutorials/multipleseasonalities.html)

**Comment by rostam** [comment]
Hi @Yibei990826 , thank you very much for the answer.
