### ISSUE TITLE
Generating Data using TimeGPT

### ISSUE THREAD

**Issue by Gaurav7888** [Nixtla/nixtla#217]
How to use timegpt to finetune on our data and then generate data using it?

**Comment by Yibei990826** [comment]
Hi @Gaurav7888! Thank you for using TimeGPT. It would be great if you can describe more about the problem.
If you mean finetune the model and make forecast, please refer to the finetune documentation [here](https://docs.nixtla.io/docs/finetuning)

**Comment by Yibei990826** [comment]
I think this issue can be closed?
