### ISSUE TITLE
ApiError: status_code: 401, body: {'data': None, 'message': 'Invalid API key', 'details': 'Key not found', 'code': 'A12', 'requestID': 'D5Z4QG33EB', 'support': 'If you have questions or need support, please email ops@nixtla.io'}

### ISSUE THREAD

**Issue by ripankundu** [Nixtla/nixtla#219]
Hi ,

I am trying to use the TimeGPT. However, when I use it, I get the following error:

"ApiError: status_code: 401, body: {'data': None, 'message': 'Invalid API key', 'details': 'Key not found', 'code': 'A12', 'requestID': 'D5Z4QG33EB', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'}"

I use the same example as you provided in the read.me file. Could you please tell me if I am doing anything wrong?

**Comment by sasi2109** [comment]
follow below steps
1. Go to this page https://dashboard.nixtla.io/
2. Sign in or Sign up
3. Under API Keys option, create Create New API Key
4. set os.environ['TIMEGPT_TOKEN'] as created New API key

**Comment by elephaint** [comment]
@ripankundu It's been a while from our side, but is this issue still occuring? If so, please follow [our Quickstart guide ](https://docs.nixtla.io/docs/getting-started-timegpt_quickstart) and report back the issue you still encounter.
