### ISSUE TITLE
Does Nixtla support  time format "YYYY-MM-DD hh:mm:ss“ ？

### ISSUE THREAD

**Issue by hvacking** [Nixtla/nixtla#220]
hi , In many timeserial prediction scenarios , we need use time "YYYY-MM-DD hh:mm:ss“ as timestamp.Now it seems timeGPT only support format "YYYY-MM-DD".  Will timeGPT support this in the future?

**Comment by MMenchero** [comment]
Hi @hvacking the format "YYY-MM-DD hh:mm:ss" is currently supported as evidenced in this [tutorial](https://nixtlaverse.nixtla.io/nixtla/docs/tutorials/multiple_series.html) that uses hourly data. If you're having trouble with the format, please share with us a reproducible example.

**Comment by elephaint** [comment]
I think this issue is solved, @hvacking let us know if you have issues with the explanation offered in the tutorial.
