### ISSUE TITLE
Pydantic V2 support

### ISSUE THREAD

**Issue by Apaezmx** [Nixtla/nixtla#228]
Pydantic v2 is a breaking change wrt pydantic v1. Nixtlats uses pydantic v1 and so is incompatible with tools built with pydantic v2. Could you add support for Pydantic v2?

**Comment by Apaezmx** [comment]
Steps to reproduce:

```bash
pip install nixtlats

pip install --upgrade pydantic
```
```python
from nixtlats import timegpt
```

Breaks because nixtlats is not compatible with pydantic v2

**Comment by ricardpique-aily** [comment]
Do we know if nixtlats will be pydantic v2 compatible in the near future?

**Comment by josegaleote** [comment]
Following up this for a while, is there any updates on the compatibility with pydantic v2?
Thanks!

**Comment by josegaleote** [comment]
Hello, do you have an estimation on when nixtlats will be compatible with pydantic > 2.0.0 ?

**Comment by filopacio** [comment]
Encountering same issue. Is there any expectation for nixtlats to align with Pydantic v2 compatibility anytime soon? Thanks!!

**Comment by AzulGarza** [comment]
we are taking a look at this and should be ready in the next days🎉

**Comment by jmoralez** [comment]
Fixed by #308

**Comment by josegaleote** [comment]
Great, thank you so much!
It's the fixed already released?

**Comment by jmoralez** [comment]
> It's the fixed already released?

Yes, since 0.5.0
