### ISSUE TITLE
Depended on fudge which has an install issue for python > 3.9.6 & setuptools>57.5

### ISSUE THREAD

**Issue by muennix** [Nixtla/nixtla#231]
Installing fudge is is using 'use_2to3' which is deprecated and not supported in setuptools>57.5

Note: there is an old pull request https://github.com/fudge-py/fudge/pull/12 that would fix the issue, but I just realized that is not really maintained anymore. Perhaps consider moving to another mock framework.

I understand that you have most likely a lot of other stuff you're working on - so take it with a grain of salt. 😀 At least in my (rather complex) environment, I don't like pinning python itself of setuptools to a specific version, which makes it difficult integrate this in my work.

**Comment by jmoralez** [comment]
Hey @muennix, thanks for using nixtla. I don't think we depend on fudge, can you describe how you came to that conclusion?

**Comment by muennix** [comment]
Weird, you are correct - It's not in your repo.

I used pip to install nixtlats, which brought the timegpt.py below:

File ~/anaconda3/lib/python3.11/site-packages/nixtlats/distributed/timegpt.py:11
      9 import numpy as np
     10 import pandas as pd
---> 11 import fugue
     12 import fugue.api as fa
     13 from fugue import transform, DataFrame, FugueWorkflow, ExecutionEngine

% pip show nixtlats
Name: nixtlats
Version: 0.1.20
Summary: TimeGPT SDK
Home-page: https://github.com/Nixtla/nixtla
Author: 
Author-email: 
License: 

I will just install nixtlats manually, which should do the trick. So this is just FYI. Anyway let me know of you would like further info.

**Comment by jmoralez** [comment]
That's [fugue](https://github.com/fugue-project/fugue), not [fudge](https://github.com/fudge-py/fudge)

**Comment by muennix** [comment]
🤦🏻‍♂️ "slightly" embarrassed. Works now - thank you

**Comment by jmoralez** [comment]
No problem, happy to help!
