### ISSUE TITLE
[FEAT] Inform users when `num_partitions>1`

### ISSUE THREAD

**Issue by AzulGarza** [Nixtla/nixtla#233]
currently, when `num_partitions > 1`, the sdk returns the following information:

<img width="514" alt="image" src="https://github.com/Nixtla/nixtla/assets/10517170/5bae54b7-866a-455f-b655-87fcc61174a0">

it might be good to add information about the partitions.

**Comment by marcopeix** [comment]
Would this be the desired outcome?

<img width="411" alt="Screenshot 2024-03-14 at 11 04 51 AM" src="https://github.com/Nixtla/nixtla/assets/19268689/471424e6-b17c-43a1-9865-66866f793cf8">

**Comment by AzulGarza** [comment]
hey @marcopeix! yes, also it would be great to `logger.info` each partition, for example:

```
using 2 partitions.
partition 1 of 2
.
.
.
partition 2 of 2
.
.
.
```

**Comment by elephaint** [comment]
@AzulGarza I think we can close this as we did not merge the PR following the implementation of processing partititions in parallel?
