### ISSUE TITLE
[DOCS] add tutorial on how tu use TimeGPT for long-horizon tasks

### ISSUE THREAD

**Issue by AzulGarza** [Nixtla/nixtla#245]
the main idea is to create a tutorial based on [this](https://docs.nixtla.io/docs/faqs#long-horizon-in-time-series) section of the faqs. currently, the example there uses AirPassengers, but it would be great to use a high-frequency dataset (for instance, Hourly or SubHourly), since the long-horizon tasks are specialized in this kind of data.

**Comment by AzulGarza** [comment]
hey @marcopeix! i tagged you in this issue ;)

**Comment by marcopeix** [comment]
PR merged, tutorial is now available. Closing.
