### ISSUE TITLE
Incorporating Exogenous Variables

### ISSUE THREAD

**Issue by drRussClay** [Nixtla/nixtla#266]
Hello - I've been following along with the installation guide for TimeGPT in Python. I want to make sure I understand how to add exogenous variables to the forecast model. It seems that I can only pass an X_df that covers the forecast period, correct? 

In my current test problem, I am adding a single exogenous variable that is very highly correlated with the outcome that I am forecasting throughout the dataset. There is one exception, where the relation gets decoupled, and that is during the forecast period. I expected to see the forecast follow the trend of exogenous predictor, but it does not - it remains smooth despite the sudden change in the exogenous variable, which makes me wonder if I am adding it correctly to the forecast.

Can you confirm that X_df should only contain data for the forecast period? I get errors if try to pass an X_df with any other length.

Thank you!

**Comment by jmoralez** [comment]
Hey @drRussClay, thanks for using TimeGPT. Yes, `X_df` should contain the values of the exogenous features during the forecast period. Can you provide a small example with fake data that reproduces what you're seeing?
