### ISSUE TITLE
Forecasting financial time series at my firm

### ISSUE THREAD

**Issue by norbertweiner** [Nixtla/nixtla#269]
Hi Nixtla,

We are testing your model in our firm. We have a time series downloaded from Bloomberg and try to do forecasting. The frequency shall be daily and the horizon is one year. However, we cannot process the forecasting. 

Could you please provide sample code to process our request?

Best,

-John
[FXB_3M.csv](https://github.com/Nixtla/nixtla/files/14756734/FXB_3M.csv)

**Comment by elephaint** [comment]
Hi,

Did you try our[ Quickstart guide](https://docs.nixtla.io/docs/getting-started-timegpt_quickstart)? What is the exact code you ran and what is the error that you encountered?
