### ISSUE TITLE
LaTeX equations not rendering correctly in the documentation. 

### ISSUE THREAD

**Issue by mergenthaler** [Nixtla/nixtla#278]
As you can see in the [Fine Tune section](https://docs.nixtla.io/docs/fine_tuning_with_a_specific_loss_function) of docs.nixtla.io LaTex equations are not rendered correctly. 

<img width="840" alt="Screenshot 2024-04-02 at 7 28 39 AM" src="https://github.com/Nixtla/nixtla/assets/4086186/cda92d71-50b3-42c5-a666-d9dbd7f55640">

**Comment by elephaint** [comment]
[This has been fixed in the docs](https://docs.nixtla.io/docs/tutorials-fine_tuning_with_a_specific_loss_function)
