### ISSUE TITLE
 TypeError: string indices must be integers, not 'list'

### ISSUE THREAD

**Issue by grace001214** [Nixtla/nixtla#290]
Hi, I'm trying to use from datasetsforecast.long_horizon import LongHorizon and I get an TypeError: string indices must be integers, not 'list'，But I have converted input_set from string index to integer index, and I still have this problem, how do I fix it?
![SharedScreenshot](https://github.com/Nixtla/nixtla/assets/154234196/618b82ec-7914-4e68-a4f0-18aad04bb50f)

**Comment by elephaint** [comment]
Hi, thanks for using nixtla!

I need a bit more information - can you please share a full, standalone piece of code that reproduces the issue? (the above code is incomplete)
