### ISSUE TITLE
ApiError: status_code: 500, An error occurred: Series are too short to compute fitted values

### ISSUE THREAD

**Issue by Abcxyz0401** [Nixtla/nixtla#291]
I'm currently working on anomaly detection for my data based on the example provided by your team. However, I encountered an error message stating "An error occurred: Series are too short to compute fitted values." 

code:
anomalies_df = timegpt.detect_anomalies(cleaned_df, time_col='time', target_col='JJI', freq='D', date_features=True)
anomalies_df
error
ApiError: status_code: 500, body: {'status': 500, 'data': None, 'message': 'Request failed with status code 500', 'details': 'An error occurred: Series are too short to compute fitted values., Please contact us at ops@nixtla.io or Azul', 'code': 'B30', 'support': 'If you have questions or need support, please email ops@nixtla.io', 'requestID': '5VD38EFX2L'}

**Comment by jmoralez** [comment]
Hey. Can you please share which example you're following?

**Comment by Abcxyz0401** [comment]
Hi. This example 
https://docs.nixtla.io/docs/anomaly_detection

**Comment by jmoralez** [comment]
There's no `cleaned_df` there. Can you provide a full reproducible example?

**Comment by Abcxyz0401** [comment]
cleaned_df
>>>
                JJI	               time
0	        0.003218	       2017-04-01 00:00:00
1	        0.003560	       2017-04-01 00:00:01
2	        0.003385	       2017-04-01 00:00:02
...	...	...
776797	0.004295	       2017-04-09 23:45:50
776798	0.004431	       2017-04-09 23:45:51
>>>
anomalies_df = timegpt.detect_anomalies(cleaned_df, time_col='time', target_col='JJI', freq='D', date_features=True)
anomalies_df

**Comment by Abcxyz0401** [comment]
I just replaced your data with my data

**Comment by jmoralez** [comment]
Your frequency isn't daily there, it's second, so you should set `freq='S'` (or `freq='s'` if you're using pandas>=2.2)
