### ISSUE TITLE
Excel add-in 'Cannot read properties of undefined'

### ISSUE THREAD

**Issue by tracykteal** [Nixtla/nixtla#293]
Using the Excel add-in and data from the table on https://docs.nixtla.io/docs/timegpt-excel-support, user is receiving the error "**Cannot read properties of undefined (reading '0')**". 

Screenshots
![error1](https://github.com/Nixtla/nixtla/assets/889238/15953964-2bd7-41ef-94dc-b0fb46d0ef57)

![error2](https://github.com/Nixtla/nixtla/assets/889238/41b417ca-fac0-4d04-93fb-23a99e30801b)

**Comment by elephaint** [comment]
I can reproduce, it seems there is incorrect parsing of the input data. I can get it to produce a Forecast sheet by formatting the timestamp differently in Excel, but that sheet doesn't hold any results and gives another error `ErrorTimestamp and value ranges do not match active sheet`.

**Comment by elephaint** [comment]
@tracykteal I think this can be closed as the plugin has been completely rewritten and no longer has this bug. If it happens, users should update the plugin.
