### ISSUE TITLE
Feat: Using historical multivariate timeseries in Timegpt

### ISSUE THREAD

**Issue by DanKil82** [Nixtla/nixtla#294]
I am currently checking `TimeGPT` with multivariate timeseries data and comparing it against univariate timeseries data, hoiwever there is no difference in the forecasts.

- The univariate data has 3 cols: date, timeseries_id and the target value
- The multivaraite data has an additional column with numeric values, lets call it `mv_column`
- I know about exogeneous vars, which is supported in TimeGPT, but the `mv_column`is purely historical.

my Code:
```python
# some imports
...

    timegpt_client = TimeGPT(
        api_key=api_key
    )
    timegpt_forecast = timegpt_client.forecast(
        df = df_train,
        h = NixtlaParams.forecast_horizon,
        freq = NixtlaParams.frequency,
        time_col = NixtlaParams.time_column,
        target_col = NixtlaParams.target_column,
        id_col = NixtlaParams.key_column,
    )

```

How can i integrate multivariate features ? Or is this simply not supported ?

**Comment by elephaint** [comment]
Hi,

historical exogenous inputs are not supported in TimeGPT; i.e. TimeGPT only leverages exogenous inputs from `df` if you also supply future values for those exogenous inputs in `X_df`. Otherwise, as you witnessed, the exogenous inputs are ignored. We will add a warning for this behavior.

**Comment by DanKil82** [comment]
Thanks for the feedback. For now i think a warning would be appropriate. 

Is it planned to add this functionality ?, I can just recommend to do so (if possible). I am running a forecasting platform in a large scale industrial company serving  use cases thoughout Demand Planning, Material Planning, Manufacturing PLanning etc. and what i see, that most of my internal customers want to add historical exogeneous data, e.g. price changes, inventory levels etc.

**Comment by elephaint** [comment]
Thanks for the suggestion; Unfortunately I don't have a timeline for that atm. For now, I'd suggest to make a forecast for these exogenous too - this can be rather simple (e.g. by setting them to the last value for the entire forecast horizon, for example for price or price change), or complex by having a separate model / pipeline predicting those values.

Note that the added benefit of this is that you will be explicitly including your assumptions about these variables in the model, whereas the assumptions on these variables will be implicitly modelled if only used as a historical exogenous variable.
