### ISSUE TITLE
When the y data is missing, how to deal with? Thank you!

### ISSUE THREAD

**Issue by zhao0415** [Nixtla/nixtla#353]
How does TimeGPT deal with the missing y data? Could you please give a way to deal with it? Thank you so much!

**Comment by elephaint** [comment]
There is a [tutorial for dealing with missing values](https://docs.nixtla.io/docs/tutorials-missing_values). In short, you should make sure that there are no missing values before using TimeGPT to forecast. Thus, the missing values need to be imputed somehow.
