### ISSUE TITLE
How to evaluate the performance of the training set in the TimeGPT Model?

### ISSUE THREAD

**Issue by kestlermai** [Nixtla/nixtla#370]
Hey there, as a newbie diving into the TimeGPT tutorials (https://docs.nixtla.io/docs/getting-started-timegpt_quickstart), I've only come across performance evaluation for predictions, but I'm missing out on how to assess the trained models themselves. This has got me curious! 
If you could guide me through it, I would really appreciate it!

**Comment by elephaint** [comment]
We currently don't provide direct access to the underlying models.

Hope this helps.

**Comment by kestlermai** [comment]
Thank you for your reply
