### ISSUE TITLE
TimeGPT exogenous variables

### ISSUE THREAD

**Issue by PeterMa1** [Nixtla/nixtla#371]
Hi, i am trying to add exogenous variables to timegpt forecast. However, i am getting the following errors:
x_cols = X_df.drop(columns=["unique_id", "ds"]).columns.to_list()
AttributeError: 'Index' object has no attribute 'to_list'.

Does anyone else encounter similar problems?

**Comment by wpdonders** [comment]
You are trying to use the `to_list()` method on a Pandas `Index` object that you returned by accessing [the `columns` attribute of a pandas DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html). However, the [`Index` object](https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index) does not have such a method. You can inspect the `Index` object directly.

**Comment by PeterMa1** [comment]
Hello, i am using pandas: 0.23.4. will that cause the problem?

**Comment by elephaint** [comment]
I think `to_list()` was [only added in pandas 0.24](https://github.com/pandas-dev/pandas/issues/8826). So for your version, you should use `tolist()`. However, it's probably best to just update pandas to the latest version, to avoid further issues.
