### ISSUE TITLE
Exogenous Variables for Forecasting

### ISSUE THREAD

**Issue by yeongnamtan** [Nixtla/nixtla#380]
I need to do forecast for Dissolved Oxygen.   I have exogenous variables like weather temperature, nutrient level, etc which affect dissolved oxygen in the open sea.

What if we don't have the FUTURE values of those exogenous variables?

https://docs.nixtla.io/docs/capabilities-forecast-add_exogenous_variables:
To model with exogenous features, include them in the DataFrame you pass to the forecast method. Provide the future values of these exogenous features over the forecast horizon using the X_df parameter.

**Comment by elephaint** [comment]
Hi, apologies for the late reply.

[This tutorial](https://docs.nixtla.io/docs/tutorials-exogenous_variables) can be followed - it specifically addresses the issue where one doesn't have the future values of the exogenous.

Hope this helps.

**Comment by elephaint** [comment]
@yeongnamtan #453 will add the capability for including historical exogenous variables. The tutorials will be updated accordingly too.
