### ISSUE TITLE
Review Excel example

### ISSUE THREAD

**Issue by tracykteal** [Nixtla/nixtla#384]
User helpfully shared with us that the [Excel example](https://docs.nixtla.io/docs/reference-timegpt_excel_add_in) isn't working.

Inputs:
1. Bearer token done
2. Model timegpt-1
3. Frequency - Hourly
4. Excel column format set to d/m/yyyy h:mm for time field and numeric 2 decimals for value field.
5. Horizon -7
6. Date ranges - Selected all time values in time field B43:B59 and values range as C43:53
7. Clean EX first - Left as True , tried with False as well

Error on Make prediction button click:
"Error: Request failed with status code 500 , series must have at least 2 values."

**Comment by elephaint** [comment]
@tracykteal If I copy+paste the existing example and try it out in Excel it works for me.

**Comment by tracykteal** [comment]
Thanks, yes, I've gone through this now too. Closing.
