### ISSUE TITLE
Error in the quick start guide.

### ISSUE THREAD

**Issue by BalancingComic** [Nixtla/nixtla#385]
Hello nixtla

I am trying to test your software. And when i started and used the quick start example using the electricity short.csv doing a forecast i couldnt get it to work. the problem is that the column topics in the csv is not correct. So if you change the following row in your example: 
```
 nixtla_client.plot(df, timegpt_fcst_df, time_col='timestamp', target_col='value', level=[80, 90])
```
to this:
```
nixtla_client.plot(df, timegpt_fcst_df, time_col='ds', target_col='y', level=[80, 90])
```
it will work.

**Comment by jmoralez** [comment]
Hey. The `time_col` argument is used to identify the column that holds the times, in the case of the quickstart the name is timestamp as you can see [here](https://github.com/Nixtla/transfer-learning-time-series/blob/main/datasets/air_passengers.csv). If your data has a different column name you have to set the argument accordingly.
