### ISSUE TITLE
Covariates

### ISSUE THREAD

**Issue by ozanbarism** [Nixtla/nixtla#413]
I saw this: Add Exogenous Variables: Incorporate additional variables that might influence your predictions to enhance forecast accuracy. (E.g. Special Dates, events or prices). 

Does this mean we can use covariates? Example, I am trying to predict indoor air temperature. Can I also push outdoor air temperature to the model? If so, how can I do that?

**Comment by marcopeix** [comment]
Yes you can! Please, follow t[his tutorial](https://docs.nixtla.io/docs/tutorials-exogenous_variables) on using exogenous variables.

**Comment by elephaint** [comment]
@ozanbarism Have you been able to solve your issue with the help of the tutorial? If not, let us know.

**Comment by mergenthaler** [comment]
Closing, but feel free to re-open if you have further questions.
