### ISSUE TITLE
token request

### ISSUE THREAD

**Issue by pietroppeter** [Nixtla/nixtla#42]
from readme:

> To consume the APIs on our own infrastructure just request tokens by sending an email to [federico@nixtla.io](mailto:federico@nixtla.io) or opening a GitHub issue. We currently have free resources available for anyone interested.

Hi! I have sent a mail on Monday (with my work mail) for a token request and since I have received no follow up, I though well of trying to ping here (might have ended into spam). Let me know if having a token is still an option.

And congrats on this great work you are doing in this (and related) repo(s), even without a token I would still make sure to take it for a test drive :)

**Comment by FedericoGarza** [comment]
Hi @pietroppeter! Thank you for notifying us. I sent you an email.😉

**Comment by pietroppeter** [comment]
yep, thanks, replied! :)

**Comment by 18811449050** [comment]
I have also sent an email and submitted my interest on the official website but have not received the tokens so far

> Hi @pietroppeter! Thank you for notifying us. I sent you an email.😉
