### ISSUE TITLE
Connection to TimeGEN model deployed in Azure AI studio fails

### ISSUE THREAD

**Issue by andreasgeorgklauser** [Nixtla/nixtla#421]
Hi, 

I have successfully deployed the TimeGEN-1 model in Azure AI studio. 
Then I'm trying to connect to his model following the documentation: 
https://docs.nixtla.io/docs/deployment-azureai
It states to use the model "azureai" in case when connecting to Azure AI. 
However, this model is not supported, the forecast method throws an error. 

So I'm trying the code below without specifying a model in the forecast method. 
Then I'm getting a different exception: 

Exception has occurred: ConnectError
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)
During handling of the above exception, another exception occurred:
httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

The code I'm using is: 

import pandas as pd
from nixtla import NixtlaClient

nixtla_client = NixtlaClient(api_key = '(I pasted the api-key from Azure AI studio here)', 
                                           base_url= '(I pasted the endpoint from Azure AI studio here)')

df = pd.read_csv('https://raw.githubusercontent.com/Nixtla/transfer-learning-time-series/main/datasets/electricity-short.csv')

fcst_df = nixtla_client.forecast(df, h=24, level=[80, 90])

nixtla_client.plot(df, fcst_df, time_col='timestamp', target_col='value', level=[80, 90])

Best regards, 

Andreas

**Comment by elephaint** [comment]
Looking into this...

**Comment by elephaint** [comment]
Hi Andreas,

Just wanted to follow up on this - did you take the verification steps I suggested? Are you still experiencing the issue?

**Comment by mcasalaina** [comment]
Similar issue here, although I don't get an SSL error, I get "Key not found, verify in https://dashboard.nixtla.io/" even though I specified an Azure AI endpoint and key. What's the deal with this? The docs are clear as mud.

**Comment by mcasalaina** [comment]
(I also tried specifying a model as "azureai" but that didn't work either, saying the only supported models were TimeGEN-1 and TimeGEN-1-long-horizon)

**Comment by mcasalaina** [comment]
Update: seems like it worked when I defined the environment variables literally as in the doc - base_url = os.environ["AZURE_AI_NIXTLA_BASE_URL"]
api_key = os.environ["AZURE_AI_NIXTLA_API_KEY"].

**Comment by mergenthaler** [comment]
@marcopeix, it would be great if we made this clearer in the docs and also integrate some test in our CI/CD for Azure.
