### ISSUE TITLE
please explain  your conclusion that TS deep NN transformers performance are bad

### ISSUE THREAD

**Issue by Sandy4321** [Nixtla/nixtla#422]
great job thanks
please explain  your conclusion that TS deep NN transformers performance are bad
may you clarify what this your video
https://youtu.be/r43JnfHrmJk?t=913

from one hand you  confirm your conclusion that TS deep NN transformers performance are bad

from another hand you say
you developed ML model which uses TS deep NN transformers and it is very good

**Comment by elephaint** [comment]
Not sure specifically which statements you are referring to - can you cite them explicitly and point them out (timestamp) in the video?

**Comment by elephaint** [comment]
Hi, just wanted to follow up on this. Do you have any questions that we can answer?

I think there have been many attempts at Transformers for time series, some succesful, some less so. This also depends on how you define success (e.g. accuracy, model complexity, model size). Hence, both conclusions that you state can be made, but again, not sure what specific statement it is you are referring to.

**Comment by mergenthaler** [comment]
Closing, but feel free to re-open if you have further questions.

**Comment by Sandy4321** [comment]
> Hi, just wanted to follow up on this. Do you have any questions that we can answer?
> 
> I think there have been many attempts at Transformers for time series, some succesful, some less so. This also depends on how you define success (e.g. accuracy, model complexity, model size). Hence, both conclusions that you state can be made, but again, not sure what specific statement it is you are referring to.

main question is about accuracy

**Comment by elephaint** [comment]
> > Hi, just wanted to follow up on this. Do you have any questions that we can answer?
> > I think there have been many attempts at Transformers for time series, some succesful, some less so. This also depends on how you define success (e.g. accuracy, model complexity, model size). Hence, both conclusions that you state can be made, but again, not sure what specific statement it is you are referring to.
> 
> main question is about accuracy

Happy to answer a question about accuracy - can you please make your question specific - which models, what problem setting, which experiments, what were the results. 

The only valid answer to a generic (vague) question such as 'Is Transformers better than an ML model for forecasting' is 'it depends'. Not sure this is the answer you're seeking, but absent any relevant context this is the only valid answer.

**Comment by Sandy4321** [comment]
as I wrote above 2 weeks ago  "main question is about accuracy" 

may you explain your statement that   transformers performance are bad

per 
 your video
https://youtu.be/r43JnfHrmJk?t=913

from one hand you confirm your conclusion that TS deep NN transformers performance are bad

from another hand you say
you developed ML model which uses TS deep NN transformers and it is very good

**Comment by elephaint** [comment]
> as I wrote above 2 weeks ago "main question is about accuracy"
> 
> may you explain your statement that transformers performance are bad
> 
> per your video https://youtu.be/r43JnfHrmJk?t=913
> 
> from one hand you confirm your conclusion that TS deep NN transformers performance are bad
> 
> from another hand you say you developed ML model which uses TS deep NN transformers and it is very good

Could you point to where in the video we make these specific statements?
