### ISSUE TITLE
Anomaly Detection Deals all data as Monthly and Daily Data

### ISSUE THREAD

**Issue by khizer-kt** [Nixtla/nixtla#430]
I have some time series data that where the timesteps are recorded after few second each, when I am calling the `nixtla_client.detect_anomalies` function and passing the frequency parameter as 's' or 'S' by changing from default 'D' it still gives the error : 
 _day is out of range for month: 0.500827815, at position 0_.
Can you look into this and tell me how to use it for time series data where the timesteps are not in days.
I also went through the API Documentation but I do not see any other values for `freq` parameter with their explanation can you also check this.

**Comment by elephaint** [comment]
Thanks for reaching out. If the frequency of your data is seconds, then `freq=S` should work. I'd guess that your `time_col` contains invalid timestamps (?) 

I would be able to better help you if can provide a reproducible code snippet so that I can investigate.

**Comment by khizer-kt** [comment]
Yes its a pandas dataframe and the the datatype of the Time column is float64

**Comment by mergenthaler** [comment]
Currently, we only support `datetime`-like columns for the time index and you are passing a `float`. You could try converting your `float64` column to `datetime`. 

Clossing, but feel free to open if you have more questions.
