### ISSUE TITLE
ApiError: status_code: 500

### ISSUE THREAD

**Issue by Wzyh-32** [Nixtla/nixtla#437]
import pandas as pd
from nixtla import NixtlaClient

# 1. Instantiate the NixtlaClient
nixtla_client = NixtlaClient(api_key = '')

# 2. Read historic electricity demand data 
df = pd.read_csv('https://raw.githubusercontent.com/Nixtla/transfer-learning-time-series/main/datasets/electricity-short.csv')

# 3. Forecast the next 24 hours
fcst_df = nixtla_client.forecast(df, h=24, level=[80, 90])

when i use timegpt to forecast,the error happened:
nixtla.core.api_error.ApiError: status_code: 500, body: {'status': 500, 'data': None, 'message': 'Unexpected token \'m\', "modal-http"... is not valid JSON', 'details': 'Error occurred while making the request', 'code': 'B30', 'support': 'If you have questions or need support, please email ops@nixtla.io', 'requestID': '22MVFUCXU3', 'headers': {}}

**Comment by feiding333** [comment]
Same error!!!!!!!!!

**Comment by Wzyh-32** [comment]
> 同样的错误!!!!!!!!
Everything was fine when I used TimeGPT for predictions yesterday, but when I used it again today, the issue mentioned above occurred. I don't know what happened.

**Comment by feiding333** [comment]
@tracykteal

**Comment by Wzyh-32** [comment]
it is ok today

**Comment by AzulGarza** [comment]
hey @feiding333 @Wzyh-32! thank you for reporting. the issue was fixed. please let us know and feel free to reopen if the issue persists.
