### ISSUE TITLE
Two TimeGPT models two different results

### ISSUE THREAD

**Issue by cagaoloz** [Nixtla/nixtla#467]
### Description

I have used both the timegpt-1-long-horizon forecasts and the timegpt-1 model and both give different results. Why do the two models give very different results? Accordingly, will the solana coin fall or rise?
![image](https://github.com/user-attachments/assets/d56460e8-e1a3-4cb6-b3a4-73b663883515)

import requests
import pandas as pd
import matplotlib.pyplot as plt
from nixtla import NixtlaClient

nixtla_client = NixtlaClient(api_key='nixtla-tok-*******')
def get_eth_price_hourly():
url = 'https://min-api.cryptocompare.com/data/v2/histohour'
params = {'fsym': 'SOL', 'tsym': 'USD', 'limit': 2000}
response = requests.get(url, params=params)
data = response.json()['Data']['Data']
df = pd.DataFrame(data, columns=['time', 'close'])
df['time'] = pd.to_datetime(df['time'], unit='s')
df.rename(columns={'time': 'ds', 'close': 'y'}, inplace=True)
return df
df = get_eth_price_hourly()
fcst_df_timegpt1 = nixtla_client.forecast( df, h=24, model="timegpt-1")
fcst_df_timegpt1_long_horizon = nixtla_client.forecast( df, h=24, model="timegpt-1-long-horizon")
plt.figure(figsize=(12, 7))
plt.plot(df['ds'], df['y'], label='Actual', color='blue')
plt.plot(fcst_df_timegpt1['ds'], fcst_df_timegpt1['TimeGPT'], label='TimeGPT-1 Forecast', color='orange')
plt.plot(fcst_df_timegpt1_long_horizon['ds'], fcst_df_timegpt1_long_horizon['TimeGPT'], label='TimeGPT-1 Long-Horizon Forecast', color='red')
plt.title('SOLANA Price Forecast')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.show()

**Comment by elephaint** [comment]
I assume your question has been answered, re-open if not.
