### ISSUE TITLE
dashboard.nixtla.io shows a blank page

### ISSUE THREAD

**Issue by efisiobova** [Nixtla/nixtla#480]
I am logged but https://dashboard.nixtla.io shows a blank page so there is no way to obtain a key.

In the javascipt console I can find the messages on DqvWbffI.js:81
_no session
remove user info_

**Comment by MaartenVL** [comment]
Same for me.

**Comment by tracykteal** [comment]
Thanks @efisiobova and @MaartenVL for reporting. We're working on a fix for this.

**Comment by efisiobova** [comment]
Now is working :-) thanks 👍

**Comment by tracykteal** [comment]
This should be fixed now. Please try again and let us know if you're still having issues.

**Comment by tracykteal** [comment]
Closing, since this is now working.
