### ISSUE TITLE
[tutorial] Tutorial on improving your forecasting accuracy 

### ISSUE THREAD

**Issue by tracykteal** [Nixtla/nixtla#482]
### Description

It would be great to have a tutorial on improving your forecasting accuracy. Going through an example of starting with TimeGPT and then improving the accuracy using different approaches. 

### Link

https://github.com/Nixtla/nixtla/tree/main/nbs/docs/tutorials

**Comment by AzulGarza** [comment]
nice, this was fixed in #495 by @Yibei990826:)
