### ISSUE TITLE
Pytorch_lightning error when Importing neuralforecast library

### ISSUE THREAD

**Issue by k7e7n7t** [Nixtla/nixtla#49]
I am trying to run the neuralforecast example, but I am getting an error when I try to import the library.

![image](https://user-images.githubusercontent.com/28897326/220037259-0433cb34-3679-40a0-91e6-c6c2d4526934.png)

Thank you!

**Comment by Sandy4321** [comment]
may you share link to code sample to try ?

**Comment by FedericoGarza** [comment]
Hey! Closing this PR since this was related to a previous repo version. Now, the repo contains the python SDK to access TimeGPT. :)
