### ISSUE TITLE
objective parameter absent in the tsforecast() 

### ISSUE THREAD

**Issue by iamyihwa** [Nixtla/nixtla#51]
Hi, 
I am checking to see if objective function can enter as parameter in any of the models (in neuralforecast I could see, but not in other ones. ) 

In this example, there is objective parameter (objective = 'tweedie') for the tsforecast()
![image](https://github.com/Nixtla/nixtla/assets/12494156/f5963002-2e2b-43dd-9b26-c19fe813f171)
[source](https://github.com/Nixtla/nixtla/blob/f201a68141bc68fdc7c0f81acdcf12b78eb8401a/sdk/python-autotimeseries/README.md?plain=1#L67)

However couldn't find it in the actual implementation. 
![image](https://github.com/Nixtla/nixtla/assets/12494156/d1fbd9ed-d53a-4e04-8943-ee9be70ad519)
[link](https://github.com/Nixtla/nixtla/blob/f201a68141bc68fdc7c0f81acdcf12b78eb8401a/sdk/python-autotimeseries/autotimeseries/core.py#LL332C2-L332C2)

Just wondering ways to scale different models and weather one can specify different loss functions at this level ..

**Comment by FedericoGarza** [comment]
Hey! Closing this PR since this was related to a previous repo version. Now, the repo contains the python SDK to access TimeGPT. :)
