### ISSUE TITLE
Return Type discrepancy forecast function inside class TimeGPT in timegpt.py

### ISSUE THREAD

**Issue by Aniket-Mishra** [Nixtla/nixtla#94]
File: nixtla/nixtlats/timegpt.py
Class: TimeGPT
Function: Forecxast

Expected output for the forecast function at line 626 is pd.DataFrame. The **self._forecast** returns a pandas dataframe which is a part of the if Statement. However, when calling **_DistributedTimeGPT().forecast()**, the return type is fugue.AnyDataFrame in _nixtla/nixtlats/distributed/timegpt.py, Line 37.
A quick fix would be to do a to_pandas on top of the fugue.AnyDataFrame.

**Comment by elephaint** [comment]
@AzulGarza Not sure this is still the case, I don't think so?

**Comment by mergenthaler** [comment]
Fixed by #429.
