### ISSUE TITLE
Token limit (not used, but expired)

### ISSUE THREAD

**Issue by wadood-flextock** [Nixtla/nixtla#96]
Created a basic timeseries to predict. 
Applied the token from the https://dashboard.nixtla.io/
Was out of limit on second run (first was on error)

ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email ops@nixtla.io to continue using the API', 'code': 'A20', 'requestID': 'NGJ6Y5GZ7F', 'support': 'If you have questions or need support, please email ops@nixtla.io'}

**Comment by BasilaryGroup** [comment]
At least you were able to run it once. It now fails before completing the first run. See https://github.com/Nixtla/nixtla/issues/173

**Comment by TingTingwoaini** [comment]
> Created a basic timeseries to predict. Applied the token from the https://dashboard.nixtla.io/ Was out of limit on second run (first was on error)
> 
> ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email [ops@nixtla.io](mailto:ops@nixtla.io) to continue using the API', 'code': 'A20', 'requestID': 'NGJ6Y5GZ7F', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'}

i have the same question

**Comment by bai-lf** [comment]
zhe same question

**Comment by elephaint** [comment]
I believe this is likely no longer relevant - [you can set up an API key here](https://nixtlaverse.nixtla.io/nixtla/docs/getting-started/setting_up_your_api_key.html).
