### ISSUE TITLE
How to solve KeyError: 'TIMEGPT_ TOKEN '

### ISSUE THREAD

**Issue by yuhaoxu99** [Nixtla/nixtla#99]
When I follow the steps of readme, KeyError: 'TIMEGPT_TOKEN' bug will appear. Please can you tell me how can I solve it?

**Comment by eWizardII** [comment]
Having the same issue too.

**Comment by luoolu** [comment]
Having the same issue too.

  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'z7YUzeRn0Edu6jfUBKn.......'

**Comment by MateKristof** [comment]
You should create an .env file in the project directory and paste the API key into it. As seen here:
![image](https://github.com/Nixtla/nixtla/assets/9765439/63d01b68-6cbb-46b0-ba61-b26267a52d7a)
Then install python dotenv.
```
pip install python-dotenv
```
And use this lines in your main file to load environment:
```
from dotenv import load_dotenv
load_dotenv()
```

**Comment by elephaint** [comment]
@yuhaoxu99 See [this page](https://docs.nixtla.io/docs/getting-started-setting_up_your_api_key) for how to set up the API key
